<a href="https://colab.research.google.com/github/vortexash/BI-machine-learning/blob/master/activation_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Soft Max

In [0]:
import numpy as np

In [0]:
def softmax(L):
  expl =np.exp(L)
  sumExpl=sum(exp1)
  result=[]
  for j in epxl:
    
    result.append(j*1/sumExpl)
  return result

In [14]:
softmax(0.2,0.9,0.1)

TypeError: ignored

In [15]:
test_sm=softmax([0.2,0.9,0.11])

NameError: ignored

In [0]:

def softmax2(L):
  expl=np.exp(L)
  return np.divide(expl,expl.sum())
    

In [0]:
test_sn2_=softmax2([-1,2.2,4])

In [23]:
test_sn2==test_sn2_

array([ True,  True,  True])

# Sigmoid function

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [25]:
sigmoid(np.array([1,2,3]))

array([0.73105858, 0.88079708, 0.95257413])

In [0]:
sig_test=sigmoid(np.array([1,2,3]))

In [28]:
sum(sig_test)

2.5644297834303207

In [0]:
def sigmoid_der(x):
  return sigmoid(x)*(1-sigmoid(x))

In [0]:
learnrate=0.5
x =np.array([1,2,3,4])
y=np.array(0.5)

In [0]:
w=np.array([0.2,0.3,0.5,0.1])

In [33]:
np.dot(x,w)

2.6999999999999997

In [0]:
h=np.dot(x,w)

In [0]:
nout=sigmoid(h)

In [0]:
error=y-nout

In [0]:
error_term=error * sigmoid_der(h)

In [0]:
delta_weight = learnrate * error_term*x

In [51]:
nout

0.4044832623390387

In [52]:
delta_weight

array([0.01150387, 0.02300774, 0.03451161, 0.04601549])

In [0]:
h=np.dot(x,delta_weight)